version: '3.8'

services:
  app:
    build: .
    ports:
      - "5418:5418"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis

  mongo:
    container_name: mongo-container
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    container_name: redis-container
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mongo-data:
